M48
; DRILL file {KiCad 8.0.2} date 2024-06-20T15:08:58+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-20T15:08:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.8425Y-2.4409
X4.8425Y-5.3937
X7.0866Y-2.4409
X7.0866Y-5.3937
M30
